//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public @class()
        {
            this.customer_pay_class = new HashSet<customer_pay_class>();
            this.class_review = new HashSet<class_review>();
            this.class_type = new HashSet<class_type>();
            this.timetables = new HashSet<timetable>();
        }
    
        public int class_id { get; set; }
        public Nullable<int> capacity { get; set; }
        public string class_level { get; set; }
        public Nullable<int> coach_id { get; set; }
        public string class_name { get; set; }
    
        public virtual coach coach { get; set; }
        public virtual ICollection<customer_pay_class> customer_pay_class { get; set; }
        public virtual ICollection<class_review> class_review { get; set; }
        public virtual ICollection<class_type> class_type { get; set; }
        public virtual ICollection<timetable> timetables { get; set; }
    }
}
