//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.class_review = new HashSet<class_review>();
            this.payments = new HashSet<payment>();
            this.customer_pay_class = new HashSet<customer_pay_class>();
        }
    
        public int customer_id { get; set; }
        public string customer_type { get; set; }
    
        public virtual ICollection<class_review> class_review { get; set; }
        public virtual person person { get; set; }
        public virtual guest guest { get; set; }
        public virtual member member { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<customer_pay_class> customer_pay_class { get; set; }
    }
}
