//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class floor_coach
    {
        public int floor_coach_id { get; set; }
        public Nullable<int> salary { get; set; }
    
        public virtual coach coach { get; set; }
    }
}
