//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrator
    {
        public administrator()
        {
            this.branches = new HashSet<branch>();
        }
    
        public int admin_id { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual ICollection<branch> branches { get; set; }
    }
}
