//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_review
    {
        public int class_review_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual customer customer { get; set; }
        public virtual review review { get; set; }
    }
}
