//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class coach
    {
        public coach()
        {
            this.classes = new HashSet<@class>();
            this.coach_speciality = new HashSet<coach_speciality>();
        }
    
        public int coach_id { get; set; }
    
        public virtual ICollection<@class> classes { get; set; }
        public virtual staff staff { get; set; }
        public virtual floor_coach floor_coach { get; set; }
        public virtual private_coach private_coach { get; set; }
        public virtual ICollection<coach_speciality> coach_speciality { get; set; }
    }
}
