//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class fitness_information
    {
        public int info_id { get; set; }
        public Nullable<int> weight_ { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> goal_weight { get; set; }
        public int member_id { get; set; }
    
        public virtual member member { get; set; }
    }
}
