//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.fitness_information = new HashSet<fitness_information>();
        }
    
        public int member_id { get; set; }
        public Nullable<System.DateTime> membership_start_date { get; set; }
        public Nullable<System.DateTime> membership_end_date { get; set; }
        public Nullable<bool> membership_renewable { get; set; }
        public string membership_type { get; set; }
        public Nullable<int> membership_cost { get; set; }
        public Nullable<int> private_coach_id { get; set; }
        public Nullable<int> Receptionist_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<fitness_information> fitness_information { get; set; }
        public virtual private_coach private_coach { get; set; }
        public virtual receptionist receptionist { get; set; }
    }
}
