//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.person_phonenumber = new HashSet<person_phonenumber>();
        }
    
        public int person_id { get; set; }
        public string gender { get; set; }
        public string passwordd { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string person_type { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<person_phonenumber> person_phonenumber { get; set; }
        public virtual staff staff { get; set; }
    }
}
