//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_phonenumber
    {
        public int person_id { get; set; }
        public int phonenumber { get; set; }
    
        public virtual person person { get; set; }
    }
}
