//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class private_coach
    {
        public private_coach()
        {
            this.members = new HashSet<member>();
            this.timetables = new HashSet<timetable>();
        }
    
        public int private_coach_id { get; set; }
        public Nullable<int> session_price { get; set; }
    
        public virtual coach coach { get; set; }
        public virtual ICollection<member> members { get; set; }
        public virtual ICollection<timetable> timetables { get; set; }
    }
}
