//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class receptionist
    {
        public receptionist()
        {
            this.members = new HashSet<member>();
            this.payments = new HashSet<payment>();
        }
    
        public int receptionist_id { get; set; }
    
        public virtual ICollection<member> members { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual staff staff { get; set; }
    }
}
