//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staff_id { get; set; }
        public string role { get; set; }
    
        public virtual administrator administrator { get; set; }
        public virtual coach coach { get; set; }
        public virtual person person { get; set; }
        public virtual receptionist receptionist { get; set; }
    }
}
