//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_gym_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public timetable()
        {
            this.classes = new HashSet<@class>();
            this.private_coach = new HashSet<private_coach>();
        }
    
        public int timetable_id { get; set; }
        public Nullable<System.DateTime> next_date { get; set; }
        public string week_day { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
    
        public virtual ICollection<@class> classes { get; set; }
        public virtual ICollection<private_coach> private_coach { get; set; }
    }
}
